version: "0.2"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 292875404443.dkr.ecr.us-west-2.amazonaws.com/cryptoeye
      - IMAGE_TAG=$(cat version)-$(git describe --always --long)
  build:
    commands:
      - echo Building image 292875404443.dkr.ecr.us-west-2.amazonaws.com/cryptoeye:$IMAGE_TAG
      - docker build -t 292875404443.dkr.ecr.us-west-2.amazonaws.com/cryptoeye:${IMAGE_TAG}  .
  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push 292875404443.dkr.ecr.us-west-2.amazonaws.com/cryptoeye:${IMAGE_TAG} 
      - echo "Updating Lambda function to new image..."
      - echo "aws --profile cryptoeye lambda update-function-code --function-name cryptoeye --image-uri 292875404443.dkr.ecr.us-west-2.amazonaws.com/cryptoeye:${IMAGE_TAG} --region us-west-2"
      - aws lambda update-function-code --function-name cryptoeye --image-uri 292875404443.dkr.ecr.us-west-2.amazonaws.com/cryptoeye:${IMAGE_TAG} --region us-west-2
      - echo "292875404443.dkr.ecr.us-west-2.amazonaws.com/cryptoeye:${IMAGE_TAG}" > image-detail.json
artifacts:
  files:
    - image-detail.json