- include_tasks: "aws_ecr_login.yaml"

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- name: "Task:: ansible.builtin.docker_container: Deploing container: {{ cryptoeye_image }}"
  ansible.builtin.docker_container:
    name: cryptoeye
    network_mode: host
    image: "{{ cryptoeye_image }}"
    restart_policy: always
    env:
      ETHERSCAN_API_KEY: "{{ cryptoeye_etherscan_api_key }}"
      LOG_DEBUG: "on"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_module.html
- name: "Task:: ansible.builtint.wait_for: waiting for port to be open 8080"
  ansible.builtin.wait_for:
    port: 8080

- include_tasks: "smoke_test.yaml"