- name: "on"
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { mode: "0755", path: "/data" }
    - { mode: "0755", path: "/data/chaineye" }
    - { mode: "0777", path: "/data/chaineye/logs" }

- include_tasks: "aws_ecr_login.yaml"

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- name: "Task:: ansible.builtin.docker_container: Deploing container: {{ chaineye_api_image }}"
  ansible.builtin.docker_container:
    name: chaineye-api
    network_mode: host
    image: "{{ chaineye_registry }}/{{ chaineye_api_image }}"
    restart_policy: always
    volumes:
      - "/data/chaineye/logs:/var/log:rw"
    env:
      ETHERSCAN_API_KEY: "{{ chaineye_etherscan_api_key }}"
      LOG_DEBUG: "on"
      BOT_TOKEN: "{{ chaineye_bot_token }}"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_module.html
- name: "Task:: ansible.builtint.wait_for: waiting for port to be open 8000"
  ansible.builtin.wait_for:
    port: 8000

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- name: "Task:: ansible.builtin.docker_container: Deploing container: {{ chaineye_static_image }}"
  ansible.builtin.docker_container:
    name: chaineye-static
    network_mode: host
    image: "{{ chaineye_registry }}/{{ chaineye_static_image }}"
    restart_policy: always

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_module.html
- name: "Task:: ansible.builtint.wait_for: waiting for port to be open 8080"
  ansible.builtin.wait_for:
    port: 8080

- include_tasks: "smoke_test.yaml"
