# Base and only playbook to make a configuration on
# all hosts.
- hosts: chaineye-0
  become: true
  
  # At current time not sure do we need it
  gather_facts: yes

  roles:

    - name: "Grub configuration"
      role: grub
      tags:
        - grub

    - name: "Hostname configuration"
      role: hostname
      tags:
        - hostname

    - name: "NTP configuration"
      role: ntp
      tags:
        - ntp

    - name: "Amazon Web Services SSM agent"
      role: amazon-ssm-agent
      tags:
        - ssm

    - name: "Docker installation and configuration"
      role: docker
      vars:
        docker_users:
          - ec2-user
      tags:
        - docker

    - name: "Chaineye installation and configuration"
      role: chaineye
      tags:
        - chaineye
