chaineye_etherscan_api_key: "{{ lookup('pipe', 'op item get etherscan --vault chaineye --account BQ7QSXSGEBB33GR2B4EARQO6QM --field password --reveal') }}"
chaineye_bot_token: "{{ lookup('pipe', 'op item get bot_chaineyeio --vault chaineye --account BQ7QSXSGEBB33GR2B4EARQO6QM --field password --reveal') }}"

chaineye_registry: "292875404443.dkr.ecr.us-west-2.amazonaws.com"
chaineye_api_image: "chaineye:v2.0-9ab9595"
chaineye_static_image: "chaineye-site:v2.0-9ab9595"